name: Node CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.0.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.0.0
      - name: yarn install and test base64
        run: |
          pushd base64
          yarn
          yarn test
          popd
        env:
          CI: true
      - name: yarn install and test login
        run: |
          pushd login
          yarn
          yarn test
          popd
        env:
          CI: true
